In [1]:
import os
import pandas as pd
import yaml

# from tsv2bedRMod import bid_mouse2bedRMod, bid_human2bedRMod, etam2bedRMod, csv2bedRMod
from tsv2bedRMod import csv2bedRMod

from helper import write_header
from helper import get_modification_color
from helper import parse_excel

In [4]:
keys = parse_excel("/home/annebusch/anne02/euf-data/rbs-seq/GSE90963_Table_S3-m1A_candidate_sites.xlsx")
keys

dict_keys(['Table Legends & Header Info', '1. Candidate m1A sites', '2. All A sites with mut(hg19)', '3. All A sites with mut(rep)'])

In [6]:
# not sure how to handle this. Also most of it is tRNA which Sci-Modom can't handle, yet
df = pd.read_excel("/home/annebusch/anne02/euf-data/rbs-seq/GSE90963_Table_S3-m1A_candidate_sites.xlsx", sheet_name="1. Candidate m1A sites")
df

,Coordinate,Comments,Gene,Biotype,Strand,Base,BS_Depth,BS_A,BS_C,BS_G,...,Fold (NBS/BS).1,NBS_Depth,NBS_A,NBS_C,NBS_G,NBS_T,NBS_Mut,NBS_%C,NBS_%G,NBS_%T
0,NR_145822.1:12,.,28S,rRNA,+,A,816923,813695,733,1487,...,2.990034,1023372,1016782,1992,3379,1219,0.006439,0.001947,0.003302,0.001191
1,NR_145822.1:1322,.,28S,rRNA,+,A,197730,188581,102,2959,...,8.150468,26665,14725,88,4280,7572,0.447778,0.003300,0.160510,0.283968
2,tRNA_11:60,.,Homo_sapiens_nmt-tRNA-Leu-TAA-1-1 (tRNAscan-SE...,tRNA,+,A,387,386,1,0,...,201.656000,625,170,0,12,443,0.728000,0.000000,0.019200,0.708800
3,tRNA_41:36,.,Homo_sapiens_tRNA-Ala-AGC-4-1 (tRNAscan-SE ID:...,tRNA,+,A,1155,1139,0,13,...,13.694228,641,489,8,51,93,0.237129,0.012480,0.079563,0.145086
4,tRNA_48:36,.,Homo_sapiens_tRNA-Ala-CGC-1-1 (tRNAscan-SE ID:...,tRNA,+,A,481,462,0,18,...,50.517572,313,179,3,39,92,0.428115,0.009585,0.124601,0.293930
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,tRNA_434:58,.,Homo_sapiens_tRNA-Val-TAC-1-1 (tRNAscan-SE ID:...,tRNA,+,A,37244,37182,1,37,...,5.416748,7556,7453,2,49,52,0.013632,0.000265,0.006485,0.006882
87,tRNA_435:58,.,Homo_sapiens_tRNA-Val-TAC-2-1 (tRNAscan-SE ID:...,tRNA,+,A,37140,37084,3,32,...,7.930725,6313,6193,4,64,52,0.019008,0.000634,0.010138,0.008237
88,tRNA_436:26,.,Homo_sapiens_tRNA-Val-TAC-3-1 (tRNAscan-SE ID:...,tRNA,+,A,6512,6368,24,3,...,2.354088,1242,1183,29,1,29,0.047504,0.023349,0.000805,0.023349
89,tRNA_436:58,.,Homo_sapiens_tRNA-Val-TAC-3-1 (tRNAscan-SE ID:...,tRNA,+,A,2009,2000,0,7,...,15.504202,476,431,1,36,8,0.094538,0.002101,0.075630,0.016807
90,snoRNA_130:86,.,SNORD22;snoID_0137,snoRNA,+,T,14270,14245,5,10,...,8.584855,931,916,6,8,1,0.016112,0.006445,0.008593,0.001074

In [18]:
for row in df["Gene"]:
    
    if len(row.split(":")) == 4:
        # print(row.split(":"))
        homo, chrom, positions, sc = row.split(":")
        
    else: # if longer than 4, then there are two exons
        print(row.split(":"))
    row = row.split(":")

['28S']
['28S']
['Homo_sapiens_tRNA-Arg-ACG-1-1 (tRNAscan-SE ID', ' chr6.trna6) chr6', '26328368-26328440 (+) Arg (ACG) 73 bp Sc', ' 65.8;Homo_sapiens_tRNA-Arg-ACG-1-2 (tRNAscan-SE ID', ' chr6.trna8) chr6', '26537726-26537798 (+) Arg (ACG) 73 bp Sc', ' 65.8;Homo_sapiens_tRNA-Arg-ACG-1-3 (tRNAscan-SE ID', ' chr14.trna7) chr14', '23398910-23398982 (+) Arg (ACG) 73 bp Sc', ' 65.8']
['Homo_sapiens_tRNA-Arg-CCG-1-1 (tRNAscan-SE ID', ' chr6.trna115) chr6', '28710729-28710801 (-) Arg (CCG) 73 bp Sc', ' 64.7;Homo_sapiens_tRNA-Arg-CCG-1-2 (tRNAscan-SE ID', ' chr6.trna72) chr6', '28849165-28849237 (+) Arg (CCG) 73 bp Sc', ' 64.7;Homo_sapiens_tRNA-Arg-CCG-1-3 (tRNAscan-SE ID', ' chr16.trna2) chr16', '3200675-3200747 (+) Arg (CCG) 73 bp Sc', ' 64.7']
['Homo_sapiens_tRNA-Asn-GTT-2-1 (tRNAscan-SE ID', ' chr1.trna27) chr1', '148248115-148248188 (+) Asn (GTT) 74 bp Sc', ' 76.2;Homo_sapiens_tRNA-Asn-GTT-2-2 (tRNAscan-SE ID', ' chr1.trna76) chr1', '161397867-161397940 (-) Asn (GTT) 74 bp Sc', ' 76.2;Homo_sapiens_tRNA-Asn-GTT-2-3 (tRNAscan-SE ID', ' chr10.trna5) chr10', '22518438-22518511 (-) Asn (GTT) 74 bp Sc', ' 76.2;Homo_sapiens_tRNA-Asn-GTT-2-4 (tRNAscan-SE ID', ' chr13.trna5) chr13', '31248101-31248174 (-) Asn (GTT) 74 bp Sc', ' 76.2;Homo_sapiens_tRNA-Asn-GTT-2-5 (tRNAscan-SE ID', ' chr17.trna30) chr17', '36908034-36908107 (-) Asn (GTT) 74 bp Sc', ' 76.2;Homo_sapiens_tRNA-Asn-GTT-2-6 (tRNAscan-SE ID', ' chr19.trna1) chr19', '1383562-1383635 (+) Asn (GTT) 74 bp Sc', ' 76.2']
['Homo_sapiens_tRNA-Asn-GTT-3-1 (tRNAscan-SE ID', ' chr1.trna98) chr1', '148598314-148598387 (-) Asn (GTT) 74 bp Sc', ' 74.1;Homo_sapiens_tRNA-Asn-GTT-3-2 (tRNAscan-SE ID', ' chr1.trna97) chr1', '148760356-148760429 (-) Asn (GTT) 74 bp Sc', ' 74.1']
['Homo_sapiens_tRNA-Gln-CTG-1-1 (tRNAscan-SE ID', ' chr6.trna1) chr6', '18836402-18836473 (+) Gln (CTG) 72 bp Sc', ' 70.6;Homo_sapiens_tRNA-Gln-CTG-1-2 (tRNAscan-SE ID', ' chr6.trna49) chr6', '27487308-27487379 (+) Gln (CTG) 72 bp Sc', ' 70.6;Homo_sapiens_tRNA-Gln-CTG-1-3 (tRNAscan-SE ID', ' chr6.trna99) chr6', '28909378-28909449 (-) Gln (CTG) 72 bp Sc', ' 70.6;Homo_sapiens_tRNA-Gln-CTG-1-4 (tRNAscan-SE ID', ' chr15.trna8) chr15', '66161400-66161471 (-) Gln (CTG) 72 bp Sc', ' 70.6;Homo_sapiens_tRNA-Gln-CTG-1-5 (tRNAscan-SE ID', ' chr17.trna2) chr17', '8023070-8023141 (+) Gln (CTG) 72 bp Sc', ' 70.6']
['Homo_sapiens_tRNA-Gly-CCC-1-1 (tRNAscan-SE ID', ' chr1.trna122) chr1', '16872434-16872504 (-) Gly (CCC) 71 bp Sc', ' 75.5;Homo_sapiens_tRNA-Gly-CCC-1-2 (tRNAscan-SE ID', ' chr1.trna4) chr1', '17188416-17188486 (+) Gly (CCC) 71 bp Sc', ' 75.5']
['Homo_sapiens_tRNA-Gly-GCC-1-1 (tRNAscan-SE ID', ' chr1.trna34) chr1', '161413094-161413164 (+) Gly (GCC) 71 bp Sc', ' 79.9;Homo_sapiens_tRNA-Gly-GCC-1-2 (tRNAscan-SE ID', ' chr1.trna36) chr1', '161420467-161420537 (+) Gly (GCC) 71 bp Sc', ' 79.9;Homo_sapiens_tRNA-Gly-GCC-1-3 (tRNAscan-SE ID', ' chr1.trna38) chr1', '161427898-161427968 (+) Gly (GCC) 71 bp Sc', ' 79.9;Homo_sapiens_tRNA-Gly-GCC-1-4 (tRNAscan-SE ID', ' chr1.trna40) chr1', '161435258-161435328 (+) Gly (GCC) 71 bp Sc', ' 79.9;Homo_sapiens_tRNA-Gly-GCC-1-5 (tRNAscan-SE ID', ' chr21.trna1) chr21', '18827107-18827177 (-) Gly (GCC) 71 bp Sc', ' 79.9']
['Homo_sapiens_tRNA-Gly-GCC-2-1 (tRNAscan-SE ID', ' chr1.trna61) chr1', '161493637-161493707 (-) Gly (GCC) 71 bp Sc', ' 77.9;Homo_sapiens_tRNA-Gly-GCC-2-2 (tRNAscan-SE ID', ' chr2.trna17) chr2', '157257659-157257729 (-) Gly (GCC) 71 bp Sc', ' 77.9;Homo_sapiens_tRNA-Gly-GCC-2-3 (tRNAscan-SE ID', ' chr6.trna129) chr6', '27870686-27870756 (-) Gly (GCC) 71 bp Sc', ' 77.9;Homo_sapiens_tRNA-Gly-GCC-2-4 (tRNAscan-SE ID', ' chr16.trna24) chr16', '70812942-70813012 (-) Gly (GCC) 71 bp Sc', ' 77.9;Homo_sapiens_tRNA-Gly-GCC-2-5 (tRNAscan-SE ID', ' chr16.trna20) chr16', '70823410-70823480 (+) Gly (GCC) 71 bp Sc', ' 77.9;Homo_sapiens_tRNA-Gly-GCC-2-6 (tRNAscan-SE ID', ' chr17.trna4) chr17', '8029064-8029134 (+) Gly (GCC) 71 bp Sc', ' 77.9']
['Homo_sapiens_tRNA-Gly-TCC-2-1 (tRNAscan-SE ID', ' chr1.trna107) chr1', '145397864-145397935 (-) Gly (TCC) 72 bp Sc', ' 71.6;Homo_sapiens_tRNA-Gly-TCC-2-2 (tRNAscan-SE ID', ' chr1.trna72) chr1', '161417375-161417446 (-) Gly (TCC) 72 bp Sc', ' 71.6;Homo_sapiens_tRNA-Gly-TCC-2-3 (tRNAscan-SE ID', ' chr1.trna69) chr1', '161424756-161424827 (-) Gly (TCC) 72 bp Sc', ' 71.6;Homo_sapiens_tRNA-Gly-TCC-2-4 (tRNAscan-SE ID', ' chr1.trna66) chr1', '161432166-161432237 (-) Gly (TCC) 72 bp Sc', ' 71.6;Homo_sapiens_tRNA-Gly-TCC-2-5 (tRNAscan-SE ID', ' chr1.trna63) chr1', '161439547-161439618 (-) Gly (TCC) 72 bp Sc', ' 71.6;Homo_sapiens_tRNA-Gly-TCC-2-6 (tRNAscan-SE ID', ' chr1.trna43) chr1', '161500903-161500974 (+) Gly (TCC) 72 bp Sc', ' 71.6']
['Homo_sapiens_tRNA-His-GTG-1-1 (tRNAscan-SE ID', ' chr1.trna108) chr1', '145396881-145396952 (-) His (GTG) 72 bp Sc', ' 60.6;Homo_sapiens_tRNA-His-GTG-1-2 (tRNAscan-SE ID', ' chr1.trna18) chr1', '146544773-146544844 (+) His (GTG) 72 bp Sc', ' 60.6;Homo_sapiens_tRNA-His-GTG-1-3 (tRNAscan-SE ID', ' chr1.trna22) chr1', '147753471-147753542 (+) His (GTG) 72 bp Sc', ' 60.6;Homo_sapiens_tRNA-His-GTG-1-4 (tRNAscan-SE ID', ' chr1.trna100) chr1', '147774845-147774916 (-) His (GTG) 72 bp Sc', ' 60.6;Homo_sapiens_tRNA-His-GTG-1-5 (tRNAscan-SE ID', ' chr6.trna32) chr6', '27125906-27125977 (+) His (GTG) 72 bp Sc', ' 60.6;Homo_sapiens_tRNA-His-GTG-1-6 (tRNAscan-SE ID', ' chr9.trna9) chr9', '14433938-14434009 (-) His (GTG) 72 bp Sc', ' 60.6;Homo_sapiens_tRNA-His-GTG-1-7 (tRNAscan-SE ID', ' chr15.trna10) chr15', '45490804-45490875 (-) His (GTG) 72 bp Sc', ' 60.6;Homo_sapiens_tRNA-His-GTG-1-8 (tRNAscan-SE ID', ' chr15.trna9) chr15', '45492611-45492682 (-) His (GTG) 72 bp Sc', ' 60.6;Homo_sapiens_tRNA-His-GTG-1-9 (tRNAscan-SE ID', ' chr15.trna1) chr15', '45493349-45493420 (+) His (GTG) 72 bp Sc', ' 60.6']
['Homo_sapiens_tRNA-Ile-AAT-5-1 (tRNAscan-SE ID', ' chr6.trna11) chr6', '26554350-26554423 (+) Ile (AAT) 74 bp Sc', ' 80.0;Homo_sapiens_tRNA-Ile-AAT-5-2 (tRNAscan-SE ID', ' chr6.trna159) chr6', '27144994-27145067 (-) Ile (AAT) 74 bp Sc', ' 80.0;Homo_sapiens_tRNA-Ile-AAT-5-3 (tRNAscan-SE ID', ' chr6.trna155) chr6', '27205350-27205423 (-) Ile (AAT) 74 bp Sc', ' 80.0;Homo_sapiens_tRNA-Ile-AAT-5-4 (tRNAscan-SE ID', ' chr14.trna12) chr14', '102783429-102783502 (+) Ile (AAT) 74 bp Sc', ' 80.0;Homo_sapiens_tRNA-Ile-AAT-5-5 (tRNAscan-SE ID', ' chr17.trna8) chr17', '8090911-8090984 (+) Ile (AAT) 74 bp Sc', ' 80.0']
['Homo_sapiens_tRNA-Ile-AAT-7-1 (tRNAscan-SE ID', ' chr6.trna166) chr6', '26721221-26721294 (-) Ile (AAT) 74 bp Sc', ' 80.0;Homo_sapiens_tRNA-Ile-AAT-7-2 (tRNAscan-SE ID', ' chr6.trna27) chr6', '26780832-26780905 (+) Ile (AAT) 74 bp Sc', ' 80.0']
['Homo_sapiens_tRNA-iMet-CAT-1-1 (tRNAscan-SE ID', ' chr1.trna31) chr1', '153643726-153643797 (+) Met (CAT) 72 bp Sc', ' 67.7;Homo_sapiens_tRNA-iMet-CAT-1-2 (tRNAscan-SE ID', ' chr6.trna2) chr6', '26286754-26286825 (+) Met (CAT) 72 bp Sc', ' 67.7;Homo_sapiens_tRNA-iMet-CAT-1-3 (tRNAscan-SE ID', ' chr6.trna172) chr6', '26313352-26313423 (-) Met (CAT) 72 bp Sc', ' 67.7;Homo_sapiens_tRNA-iMet-CAT-1-4 (tRNAscan-SE ID', ' chr6.trna170) chr6', '26330529-26330600 (-) Met (CAT) 72 bp Sc', ' 67.7;Homo_sapiens_tRNA-iMet-CAT-1-5 (tRNAscan-SE ID', ' chr6.trna151) chr6', '27300764-27300835 (-) Met (CAT) 72 bp Sc', ' 67.7;Homo_sapiens_tRNA-iMet-CAT-1-6 (tRNAscan-SE ID', ' chr6.trna143) chr6', '27560600-27560671 (-) Met (CAT) 72 bp Sc', ' 67.7;Homo_sapiens_tRNA-iMet-CAT-1-7 (tRNAscan-SE ID', ' chr6.trna130) chr6', '27870271-27870342 (-) Met (CAT) 72 bp Sc', ' 67.7;Homo_sapiens_tRNA-iMet-CAT-1-8 (tRNAscan-SE ID', ' chr17.trna18) chr17', '80452597-80452668 (-) Met (CAT) 72 bp Sc', ' 67.7']
['Homo_sapiens_tRNA-Leu-AAG-1-1 (tRNAscan-SE ID', ' chr5.trna22) chr5', '180524474-180524555 (-) Leu (AAG) 82 bp Sc', ' 76.4;Homo_sapiens_tRNA-Leu-AAG-1-2 (tRNAscan-SE ID', ' chr5.trna6) chr5', '180528840-180528921 (+) Leu (AAG) 82 bp Sc', ' 76.4;Homo_sapiens_tRNA-Leu-AAG-1-3 (tRNAscan-SE ID', ' chr5.trna19) chr5', '180601044-180601125 (-) Leu (AAG) 82 bp Sc', ' 76.4']
['Homo_sapiens_tRNA-Leu-CAG-1-1 (tRNAscan-SE ID', ' chr1.trna33) chr1', '161411323-161411405 (+) Leu (CAG) 83 bp Sc', ' 83.1;Homo_sapiens_tRNA-Leu-CAG-1-2 (tRNAscan-SE ID', ' chr1.trna35) chr1', '161418741-161418823 (+) Leu (CAG) 83 bp Sc', ' 83.1;Homo_sapiens_tRNA-Leu-CAG-1-3 (tRNAscan-SE ID', ' chr1.trna37) chr1', '161426122-161426204 (+) Leu (CAG) 83 bp Sc', ' 83.1;Homo_sapiens_tRNA-Leu-CAG-1-4 (tRNAscan-SE ID', ' chr1.trna39) chr1', '161433532-161433614 (+) Leu (CAG) 83 bp Sc', ' 83.1;Homo_sapiens_tRNA-Leu-CAG-1-5 (tRNAscan-SE ID', ' chr1.trna41) chr1', '161440913-161440995 (+) Leu (CAG) 83 bp Sc', ' 83.1;Homo_sapiens_tRNA-Leu-CAG-1-6 (tRNAscan-SE ID', ' chr1.trna60) chr1', '161500132-161500214 (-) Leu (CAG) 83 bp Sc', ' 83.1;Homo_sapiens_tRNA-Leu-CAG-1-7 (tRNAscan-SE ID', ' chr6.trna7) chr6', '26521436-26521518 (+) Leu (CAG) 83 bp Sc', ' 83.1']
['Homo_sapiens_tRNA-Leu-CAG-2-1 (tRNAscan-SE ID', ' chr16.trna18) chr16', '57333863-57333945 (+) Leu (CAG) 83 bp Sc', ' 82.4;Homo_sapiens_tRNA-Leu-CAG-2-2 (tRNAscan-SE ID', ' chr16.trna26) chr16', '57334392-57334474 (-) Leu (CAG) 83 bp Sc', ' 82.4']
['Homo_sapiens_tRNA-Lys-CTT-1-1 (tRNAscan-SE ID', ' chr14.trna14) chr14', '58706613-58706685 (-) Lys (CTT) 73 bp Sc', ' 78.5;Homo_sapiens_tRNA-Lys-CTT-1-2 (tRNAscan-SE ID', ' chr15.trna2) chr15', '79152904-79152976 (+) Lys (CTT) 73 bp Sc', ' 78.5']
['Homo_sapiens_tRNA-Lys-CTT-2-1 (tRNAscan-SE ID', ' chr1.trna109) chr1', '145395522-145395594 (-) Lys (CTT) 73 bp Sc', ' 78.0;Homo_sapiens_tRNA-Lys-CTT-2-2 (tRNAscan-SE ID', ' chr5.trna12) chr5', '180634755-180634827 (+) Lys (CTT) 73 bp Sc', ' 78.0;Homo_sapiens_tRNA-Lys-CTT-2-3 (tRNAscan-SE ID', ' chr5.trna14) chr5', '180648979-180649051 (-) Lys (CTT) 73 bp Sc', ' 78.0;Homo_sapiens_tRNA-Lys-CTT-2-4 (tRNAscan-SE ID', ' chr6.trna13) chr6', '26556774-26556846 (+) Lys (CTT) 73 bp Sc', ' 78.0;Homo_sapiens_tRNA-Lys-CTT-2-5 (tRNAscan-SE ID', ' chr16.trna8) chr16', '3225692-3225764 (+) Lys (CTT) 73 bp Sc', ' 78.0']
['Homo_sapiens_tRNA-Met-CAT-3-1 (tRNAscan-SE ID', ' chr6.trna74) chr6', '28912352-28912424 (+) Met (CAT) 73 bp Sc', ' 74.0;Homo_sapiens_tRNA-Met-CAT-3-2 (tRNAscan-SE ID', ' chr6.trna97) chr6', '28921042-28921114 (-) Met (CAT) 73 bp Sc', ' 74.0']
['Homo_sapiens_tRNA-Phe-GAA-1-1 (tRNAscan-SE ID', ' chr6.trna110) chr6', '28758499-28758571 (-) Phe (GAA) 73 bp Sc', ' 85.2;Homo_sapiens_tRNA-Phe-GAA-1-2 (tRNAscan-SE ID', ' chr6.trna96) chr6', '28949449-28949521 (-) Phe (GAA) 73 bp Sc', ' 85.2;Homo_sapiens_tRNA-Phe-GAA-1-3 (tRNAscan-SE ID', ' chr11.trna17) chr11', '59324970-59325042 (-) Phe (GAA) 73 bp Sc', ' 85.2;Homo_sapiens_tRNA-Phe-GAA-1-4 (tRNAscan-SE ID', ' chr12.trna11) chr12', '125412389-125412461 (-) Phe (GAA) 73 bp Sc', ' 85.2;Homo_sapiens_tRNA-Phe-GAA-1-5 (tRNAscan-SE ID', ' chr13.trna1) chr13', '95201904-95201976 (-) Phe (GAA) 73 bp Sc', ' 85.2;Homo_sapiens_tRNA-Phe-GAA-1-6 (tRNAscan-SE ID', ' chr19.trna14) chr19', '1383361-1383433 (-) Phe (GAA) 73 bp Sc', ' 85.2']
['Homo_sapiens_tRNA-Pro-AGG-2-1 (tRNAscan-SE ID', ' chr1.trna58) chr1', '167684725-167684796 (-) Pro (AGG) 72 bp Sc', ' 67.7;Homo_sapiens_tRNA-Pro-AGG-2-2 (tRNAscan-SE ID', ' chr6.trna12) chr6', '26555498-26555569 (+) Pro (AGG) 72 bp Sc', ' 67.7;Homo_sapiens_tRNA-Pro-AGG-2-3 (tRNAscan-SE ID', ' chr7.trna4) chr7', '128423504-128423575 (+) Pro (AGG) 72 bp Sc', ' 67.7;Homo_sapiens_tRNA-Pro-AGG-2-4 (tRNAscan-SE ID', ' chr11.trna7) chr11', '75946557-75946628 (+) Pro (AGG) 72 bp Sc', ' 67.7;Homo_sapiens_tRNA-Pro-AGG-2-5 (tRNAscan-SE ID', ' chr14.trna24) chr14', '21077495-21077566 (-) Pro (AGG) 72 bp Sc', ' 67.7;Homo_sapiens_tRNA-Pro-AGG-2-6 (tRNAscan-SE ID', ' chr14.trna23) chr14', '21081560-21081631 (-) Pro (AGG) 72 bp Sc', ' 67.7;Homo_sapiens_tRNA-Pro-AGG-2-7 (tRNAscan-SE ID', ' chr16.trna29) chr16', '3232635-3232706 (-) Pro (AGG) 72 bp Sc', ' 67.7;Homo_sapiens_tRNA-Pro-AGG-2-8 (tRNAscan-SE ID', ' chr16.trna10) chr16', '3239634-3239705 (+) Pro (AGG) 72 bp Sc', ' 67.7']
['Homo_sapiens_tRNA-Ser-AGA-2-1 (tRNAscan-SE ID', ' chr6.trna5) chr6', '26327817-26327898 (+) Ser (AGA) 82 bp Sc', ' 89.6;Homo_sapiens_tRNA-Ser-AGA-2-2 (tRNAscan-SE ID', ' chr6.trna44) chr6', '27446591-27446672 (+) Ser (AGA) 82 bp Sc', ' 89.6;Homo_sapiens_tRNA-Ser-AGA-2-3 (tRNAscan-SE ID', ' chr6.trna46) chr6', '27463593-27463674 (+) Ser (AGA) 82 bp Sc', ' 89.6;Homo_sapiens_tRNA-Ser-AGA-2-4 (tRNAscan-SE ID', ' chr6.trna47) chr6', '27470818-27470899 (+) Ser (AGA) 82 bp Sc', ' 89.6;Homo_sapiens_tRNA-Ser-AGA-2-5 (tRNAscan-SE ID', ' chr8.trna9) chr8', '96281885-96281966 (-) Ser (AGA) 82 bp Sc', ' 89.6;Homo_sapiens_tRNA-Ser-AGA-2-6 (tRNAscan-SE ID', ' chr17.trna35) chr17', '8129928-8130009 (-) Ser (AGA) 82 bp Sc', ' 89.6']
['Homo_sapiens_tRNA-Ser-GCT-4-1 (tRNAscan-SE ID', ' chr6.trna124) chr6', '28565117-28565198 (-) Ser (GCT) 82 bp Sc', ' 88.1;Homo_sapiens_tRNA-Ser-GCT-4-2 (tRNAscan-SE ID', ' chr15.trna11) chr15', '40886023-40886104 (-) Ser (GCT) 82 bp Sc', ' 88.1;Homo_sapiens_tRNA-Ser-GCT-4-3 (tRNAscan-SE ID', ' chr17.trna6) chr17', '8090184-8090265 (+) Ser (GCT) 82 bp Sc', ' 88.1']
['Homo_sapiens_tRNA-Val-CAC-1-1 (tRNAscan-SE ID', ' chr1.trna78) chr1', '161369490-161369562 (-) Val (CAC) 73 bp Sc', ' 78.8;Homo_sapiens_tRNA-Val-CAC-1-2 (tRNAscan-SE ID', ' chr5.trna5) chr5', '180524070-180524142 (+) Val (CAC) 73 bp Sc', ' 78.8;Homo_sapiens_tRNA-Val-CAC-1-3 (tRNAscan-SE ID', ' chr5.trna21) chr5', '180529253-180529325 (-) Val (CAC) 73 bp Sc', ' 78.8;Homo_sapiens_tRNA-Val-CAC-1-4 (tRNAscan-SE ID', ' chr5.trna9) chr5', '180600650-180600722 (+) Val (CAC) 73 bp Sc', ' 78.8;Homo_sapiens_tRNA-Val-CAC-1-5 (tRNAscan-SE ID', ' chr5.trna13) chr5', '180649395-180649467 (-) Val (CAC) 73 bp Sc', ' 78.8;Homo_sapiens_tRNA-Val-CAC-1-6 (tRNAscan-SE ID', ' chr6.trna9) chr6', '26538282-26538354 (+) Val (CAC) 73 bp Sc', ' 78.8']
['Homo_sapiens_tRNA-Val-TAC-1-1 (tRNAscan-SE ID', ' chr11.trna19) chr11', '59318102-59318174 (-) Val (TAC) 73 bp Sc', ' 78.8;Homo_sapiens_tRNA-Val-TAC-1-2 (tRNAscan-SE ID', ' chrX.trna4) chrX', '18693029-18693101 (-) Val (TAC) 73 bp Sc', ' 78.8']
['SNORD22;snoID_0137']

In [21]:
for row in df["Gene"]:
    if ";" in row:
        print(row)
        print("-")

Homo_sapiens_tRNA-Arg-ACG-1-1 (tRNAscan-SE ID: chr6.trna6) chr6:26328368-26328440 (+) Arg (ACG) 73 bp Sc: 65.8;Homo_sapiens_tRNA-Arg-ACG-1-2 (tRNAscan-SE ID: chr6.trna8) chr6:26537726-26537798 (+) Arg (ACG) 73 bp Sc: 65.8;Homo_sapiens_tRNA-Arg-ACG-1-3 (tRNAscan-SE ID: chr14.trna7) chr14:23398910-23398982 (+) Arg (ACG) 73 bp Sc: 65.8
-
Homo_sapiens_tRNA-Arg-CCG-1-1 (tRNAscan-SE ID: chr6.trna115) chr6:28710729-28710801 (-) Arg (CCG) 73 bp Sc: 64.7;Homo_sapiens_tRNA-Arg-CCG-1-2 (tRNAscan-SE ID: chr6.trna72) chr6:28849165-28849237 (+) Arg (CCG) 73 bp Sc: 64.7;Homo_sapiens_tRNA-Arg-CCG-1-3 (tRNAscan-SE ID: chr16.trna2) chr16:3200675-3200747 (+) Arg (CCG) 73 bp Sc: 64.7
-
Homo_sapiens_tRNA-Asn-GTT-2-1 (tRNAscan-SE ID: chr1.trna27) chr1:148248115-148248188 (+) Asn (GTT) 74 bp Sc: 76.2;Homo_sapiens_tRNA-Asn-GTT-2-2 (tRNAscan-SE ID: chr1.trna76) chr1:161397867-161397940 (-) Asn (GTT) 74 bp Sc: 76.2;Homo_sapiens_tRNA-Asn-GTT-2-3 (tRNAscan-SE ID: chr10.trna5) chr10:22518438-22518511 (-) Asn (GTT) 74 bp Sc: 76.2;Homo_sapiens_tRNA-Asn-GTT-2-4 (tRNAscan-SE ID: chr13.trna5) chr13:31248101-31248174 (-) Asn (GTT) 74 bp Sc: 76.2;Homo_sapiens_tRNA-Asn-GTT-2-5 (tRNAscan-SE ID: chr17.trna30) chr17:36908034-36908107 (-) Asn (GTT) 74 bp Sc: 76.2;Homo_sapiens_tRNA-Asn-GTT-2-6 (tRNAscan-SE ID: chr19.trna1) chr19:1383562-1383635 (+) Asn (GTT) 74 bp Sc: 76.2
-
Homo_sapiens_tRNA-Asn-GTT-3-1 (tRNAscan-SE ID: chr1.trna98) chr1:148598314-148598387 (-) Asn (GTT) 74 bp Sc: 74.1;Homo_sapiens_tRNA-Asn-GTT-3-2 (tRNAscan-SE ID: chr1.trna97) chr1:148760356-148760429 (-) Asn (GTT) 74 bp Sc: 74.1
-
Homo_sapiens_tRNA-Gln-CTG-1-1 (tRNAscan-SE ID: chr6.trna1) chr6:18836402-18836473 (+) Gln (CTG) 72 bp Sc: 70.6;Homo_sapiens_tRNA-Gln-CTG-1-2 (tRNAscan-SE ID: chr6.trna49) chr6:27487308-27487379 (+) Gln (CTG) 72 bp Sc: 70.6;Homo_sapiens_tRNA-Gln-CTG-1-3 (tRNAscan-SE ID: chr6.trna99) chr6:28909378-28909449 (-) Gln (CTG) 72 bp Sc: 70.6;Homo_sapiens_tRNA-Gln-CTG-1-4 (tRNAscan-SE ID: chr15.trna8) chr15:66161400-66161471 (-) Gln (CTG) 72 bp Sc: 70.6;Homo_sapiens_tRNA-Gln-CTG-1-5 (tRNAscan-SE ID: chr17.trna2) chr17:8023070-8023141 (+) Gln (CTG) 72 bp Sc: 70.6
-
Homo_sapiens_tRNA-Gly-CCC-1-1 (tRNAscan-SE ID: chr1.trna122) chr1:16872434-16872504 (-) Gly (CCC) 71 bp Sc: 75.5;Homo_sapiens_tRNA-Gly-CCC-1-2 (tRNAscan-SE ID: chr1.trna4) chr1:17188416-17188486 (+) Gly (CCC) 71 bp Sc: 75.5
-
Homo_sapiens_tRNA-Gly-GCC-1-1 (tRNAscan-SE ID: chr1.trna34) chr1:161413094-161413164 (+) Gly (GCC) 71 bp Sc: 79.9;Homo_sapiens_tRNA-Gly-GCC-1-2 (tRNAscan-SE ID: chr1.trna36) chr1:161420467-161420537 (+) Gly (GCC) 71 bp Sc: 79.9;Homo_sapiens_tRNA-Gly-GCC-1-3 (tRNAscan-SE ID: chr1.trna38) chr1:161427898-161427968 (+) Gly (GCC) 71 bp Sc: 79.9;Homo_sapiens_tRNA-Gly-GCC-1-4 (tRNAscan-SE ID: chr1.trna40) chr1:161435258-161435328 (+) Gly (GCC) 71 bp Sc: 79.9;Homo_sapiens_tRNA-Gly-GCC-1-5 (tRNAscan-SE ID: chr21.trna1) chr21:18827107-18827177 (-) Gly (GCC) 71 bp Sc: 79.9
-
Homo_sapiens_tRNA-Gly-GCC-2-1 (tRNAscan-SE ID: chr1.trna61) chr1:161493637-161493707 (-) Gly (GCC) 71 bp Sc: 77.9;Homo_sapiens_tRNA-Gly-GCC-2-2 (tRNAscan-SE ID: chr2.trna17) chr2:157257659-157257729 (-) Gly (GCC) 71 bp Sc: 77.9;Homo_sapiens_tRNA-Gly-GCC-2-3 (tRNAscan-SE ID: chr6.trna129) chr6:27870686-27870756 (-) Gly (GCC) 71 bp Sc: 77.9;Homo_sapiens_tRNA-Gly-GCC-2-4 (tRNAscan-SE ID: chr16.trna24) chr16:70812942-70813012 (-) Gly (GCC) 71 bp Sc: 77.9;Homo_sapiens_tRNA-Gly-GCC-2-5 (tRNAscan-SE ID: chr16.trna20) chr16:70823410-70823480 (+) Gly (GCC) 71 bp Sc: 77.9;Homo_sapiens_tRNA-Gly-GCC-2-6 (tRNAscan-SE ID: chr17.trna4) chr17:8029064-8029134 (+) Gly (GCC) 71 bp Sc: 77.9
-
Homo_sapiens_tRNA-Gly-TCC-2-1 (tRNAscan-SE ID: chr1.trna107) chr1:145397864-145397935 (-) Gly (TCC) 72 bp Sc: 71.6;Homo_sapiens_tRNA-Gly-TCC-2-2 (tRNAscan-SE ID: chr1.trna72) chr1:161417375-161417446 (-) Gly (TCC) 72 bp Sc: 71.6;Homo_sapiens_tRNA-Gly-TCC-2-3 (tRNAscan-SE ID: chr1.trna69) chr1:161424756-161424827 (-) Gly (TCC) 72 bp Sc: 71.6;Homo_sapiens_tRNA-Gly-TCC-2-4 (tRNAscan-SE ID: chr1.trna66) chr1:161432166-161432237 (-) Gly (TCC) 72 bp Sc: 71.6;Homo_sapiens_tRNA-Gly-TCC-2-5 (tRNAscan-SE ID: chr1.trna63) chr1:161439547-161439618 (-) Gly (TCC) 72 bp Sc: 71.6;Homo_sapiens_tRNA-Gly-TCC-2-6 (tRNAscan-SE ID: chr1.trna43) chr1:161500903-161500974 (+) Gly (TCC) 72 bp Sc: 71.6
-
Homo_sapiens_tRNA-His-GTG-1-1 (tRNAscan-SE ID: chr1.trna108) chr1:145396881-145396952 (-) His (GTG) 72 bp Sc: 60.6;Homo_sapiens_tRNA-His-GTG-1-2 (tRNAscan-SE ID: chr1.trna18) chr1:146544773-146544844 (+) His (GTG) 72 bp Sc: 60.6;Homo_sapiens_tRNA-His-GTG-1-3 (tRNAscan-SE ID: chr1.trna22) chr1:147753471-147753542 (+) His (GTG) 72 bp Sc: 60.6;Homo_sapiens_tRNA-His-GTG-1-4 (tRNAscan-SE ID: chr1.trna100) chr1:147774845-147774916 (-) His (GTG) 72 bp Sc: 60.6;Homo_sapiens_tRNA-His-GTG-1-5 (tRNAscan-SE ID: chr6.trna32) chr6:27125906-27125977 (+) His (GTG) 72 bp Sc: 60.6;Homo_sapiens_tRNA-His-GTG-1-6 (tRNAscan-SE ID: chr9.trna9) chr9:14433938-14434009 (-) His (GTG) 72 bp Sc: 60.6;Homo_sapiens_tRNA-His-GTG-1-7 (tRNAscan-SE ID: chr15.trna10) chr15:45490804-45490875 (-) His (GTG) 72 bp Sc: 60.6;Homo_sapiens_tRNA-His-GTG-1-8 (tRNAscan-SE ID: chr15.trna9) chr15:45492611-45492682 (-) His (GTG) 72 bp Sc: 60.6;Homo_sapiens_tRNA-His-GTG-1-9 (tRNAscan-SE ID: chr15.trna1) chr15:45493349-45493420 (+) His (GTG) 72 bp Sc: 60.6
-
Homo_sapiens_tRNA-Ile-AAT-5-1 (tRNAscan-SE ID: chr6.trna11) chr6:26554350-26554423 (+) Ile (AAT) 74 bp Sc: 80.0;Homo_sapiens_tRNA-Ile-AAT-5-2 (tRNAscan-SE ID: chr6.trna159) chr6:27144994-27145067 (-) Ile (AAT) 74 bp Sc: 80.0;Homo_sapiens_tRNA-Ile-AAT-5-3 (tRNAscan-SE ID: chr6.trna155) chr6:27205350-27205423 (-) Ile (AAT) 74 bp Sc: 80.0;Homo_sapiens_tRNA-Ile-AAT-5-4 (tRNAscan-SE ID: chr14.trna12) chr14:102783429-102783502 (+) Ile (AAT) 74 bp Sc: 80.0;Homo_sapiens_tRNA-Ile-AAT-5-5 (tRNAscan-SE ID: chr17.trna8) chr17:8090911-8090984 (+) Ile (AAT) 74 bp Sc: 80.0
-
Homo_sapiens_tRNA-Ile-AAT-7-1 (tRNAscan-SE ID: chr6.trna166) chr6:26721221-26721294 (-) Ile (AAT) 74 bp Sc: 80.0;Homo_sapiens_tRNA-Ile-AAT-7-2 (tRNAscan-SE ID: chr6.trna27) chr6:26780832-26780905 (+) Ile (AAT) 74 bp Sc: 80.0
-
Homo_sapiens_tRNA-iMet-CAT-1-1 (tRNAscan-SE ID: chr1.trna31) chr1:153643726-153643797 (+) Met (CAT) 72 bp Sc: 67.7;Homo_sapiens_tRNA-iMet-CAT-1-2 (tRNAscan-SE ID: chr6.trna2) chr6:26286754-26286825 (+) Met (CAT) 72 bp Sc: 67.7;Homo_sapiens_tRNA-iMet-CAT-1-3 (tRNAscan-SE ID: chr6.trna172) chr6:26313352-26313423 (-) Met (CAT) 72 bp Sc: 67.7;Homo_sapiens_tRNA-iMet-CAT-1-4 (tRNAscan-SE ID: chr6.trna170) chr6:26330529-26330600 (-) Met (CAT) 72 bp Sc: 67.7;Homo_sapiens_tRNA-iMet-CAT-1-5 (tRNAscan-SE ID: chr6.trna151) chr6:27300764-27300835 (-) Met (CAT) 72 bp Sc: 67.7;Homo_sapiens_tRNA-iMet-CAT-1-6 (tRNAscan-SE ID: chr6.trna143) chr6:27560600-27560671 (-) Met (CAT) 72 bp Sc: 67.7;Homo_sapiens_tRNA-iMet-CAT-1-7 (tRNAscan-SE ID: chr6.trna130) chr6:27870271-27870342 (-) Met (CAT) 72 bp Sc: 67.7;Homo_sapiens_tRNA-iMet-CAT-1-8 (tRNAscan-SE ID: chr17.trna18) chr17:80452597-80452668 (-) Met (CAT) 72 bp Sc: 67.7
-
Homo_sapiens_tRNA-Leu-AAG-1-1 (tRNAscan-SE ID: chr5.trna22) chr5:180524474-180524555 (-) Leu (AAG) 82 bp Sc: 76.4;Homo_sapiens_tRNA-Leu-AAG-1-2 (tRNAscan-SE ID: chr5.trna6) chr5:180528840-180528921 (+) Leu (AAG) 82 bp Sc: 76.4;Homo_sapiens_tRNA-Leu-AAG-1-3 (tRNAscan-SE ID: chr5.trna19) chr5:180601044-180601125 (-) Leu (AAG) 82 bp Sc: 76.4
-
Homo_sapiens_tRNA-Leu-CAG-1-1 (tRNAscan-SE ID: chr1.trna33) chr1:161411323-161411405 (+) Leu (CAG) 83 bp Sc: 83.1;Homo_sapiens_tRNA-Leu-CAG-1-2 (tRNAscan-SE ID: chr1.trna35) chr1:161418741-161418823 (+) Leu (CAG) 83 bp Sc: 83.1;Homo_sapiens_tRNA-Leu-CAG-1-3 (tRNAscan-SE ID: chr1.trna37) chr1:161426122-161426204 (+) Leu (CAG) 83 bp Sc: 83.1;Homo_sapiens_tRNA-Leu-CAG-1-4 (tRNAscan-SE ID: chr1.trna39) chr1:161433532-161433614 (+) Leu (CAG) 83 bp Sc: 83.1;Homo_sapiens_tRNA-Leu-CAG-1-5 (tRNAscan-SE ID: chr1.trna41) chr1:161440913-161440995 (+) Leu (CAG) 83 bp Sc: 83.1;Homo_sapiens_tRNA-Leu-CAG-1-6 (tRNAscan-SE ID: chr1.trna60) chr1:161500132-161500214 (-) Leu (CAG) 83 bp Sc: 83.1;Homo_sapiens_tRNA-Leu-CAG-1-7 (tRNAscan-SE ID: chr6.trna7) chr6:26521436-26521518 (+) Leu (CAG) 83 bp Sc: 83.1
-
Homo_sapiens_tRNA-Leu-CAG-2-1 (tRNAscan-SE ID: chr16.trna18) chr16:57333863-57333945 (+) Leu (CAG) 83 bp Sc: 82.4;Homo_sapiens_tRNA-Leu-CAG-2-2 (tRNAscan-SE ID: chr16.trna26) chr16:57334392-57334474 (-) Leu (CAG) 83 bp Sc: 82.4
-
Homo_sapiens_tRNA-Lys-CTT-1-1 (tRNAscan-SE ID: chr14.trna14) chr14:58706613-58706685 (-) Lys (CTT) 73 bp Sc: 78.5;Homo_sapiens_tRNA-Lys-CTT-1-2 (tRNAscan-SE ID: chr15.trna2) chr15:79152904-79152976 (+) Lys (CTT) 73 bp Sc: 78.5
-
Homo_sapiens_tRNA-Lys-CTT-2-1 (tRNAscan-SE ID: chr1.trna109) chr1:145395522-145395594 (-) Lys (CTT) 73 bp Sc: 78.0;Homo_sapiens_tRNA-Lys-CTT-2-2 (tRNAscan-SE ID: chr5.trna12) chr5:180634755-180634827 (+) Lys (CTT) 73 bp Sc: 78.0;Homo_sapiens_tRNA-Lys-CTT-2-3 (tRNAscan-SE ID: chr5.trna14) chr5:180648979-180649051 (-) Lys (CTT) 73 bp Sc: 78.0;Homo_sapiens_tRNA-Lys-CTT-2-4 (tRNAscan-SE ID: chr6.trna13) chr6:26556774-26556846 (+) Lys (CTT) 73 bp Sc: 78.0;Homo_sapiens_tRNA-Lys-CTT-2-5 (tRNAscan-SE ID: chr16.trna8) chr16:3225692-3225764 (+) Lys (CTT) 73 bp Sc: 78.0
-
Homo_sapiens_tRNA-Met-CAT-3-1 (tRNAscan-SE ID: chr6.trna74) chr6:28912352-28912424 (+) Met (CAT) 73 bp Sc: 74.0;Homo_sapiens_tRNA-Met-CAT-3-2 (tRNAscan-SE ID: chr6.trna97) chr6:28921042-28921114 (-) Met (CAT) 73 bp Sc: 74.0
-
Homo_sapiens_tRNA-Phe-GAA-1-1 (tRNAscan-SE ID: chr6.trna110) chr6:28758499-28758571 (-) Phe (GAA) 73 bp Sc: 85.2;Homo_sapiens_tRNA-Phe-GAA-1-2 (tRNAscan-SE ID: chr6.trna96) chr6:28949449-28949521 (-) Phe (GAA) 73 bp Sc: 85.2;Homo_sapiens_tRNA-Phe-GAA-1-3 (tRNAscan-SE ID: chr11.trna17) chr11:59324970-59325042 (-) Phe (GAA) 73 bp Sc: 85.2;Homo_sapiens_tRNA-Phe-GAA-1-4 (tRNAscan-SE ID: chr12.trna11) chr12:125412389-125412461 (-) Phe (GAA) 73 bp Sc: 85.2;Homo_sapiens_tRNA-Phe-GAA-1-5 (tRNAscan-SE ID: chr13.trna1) chr13:95201904-95201976 (-) Phe (GAA) 73 bp Sc: 85.2;Homo_sapiens_tRNA-Phe-GAA-1-6 (tRNAscan-SE ID: chr19.trna14) chr19:1383361-1383433 (-) Phe (GAA) 73 bp Sc: 85.2
-
Homo_sapiens_tRNA-Pro-AGG-2-1 (tRNAscan-SE ID: chr1.trna58) chr1:167684725-167684796 (-) Pro (AGG) 72 bp Sc: 67.7;Homo_sapiens_tRNA-Pro-AGG-2-2 (tRNAscan-SE ID: chr6.trna12) chr6:26555498-26555569 (+) Pro (AGG) 72 bp Sc: 67.7;Homo_sapiens_tRNA-Pro-AGG-2-3 (tRNAscan-SE ID: chr7.trna4) chr7:128423504-128423575 (+) Pro (AGG) 72 bp Sc: 67.7;Homo_sapiens_tRNA-Pro-AGG-2-4 (tRNAscan-SE ID: chr11.trna7) chr11:75946557-75946628 (+) Pro (AGG) 72 bp Sc: 67.7;Homo_sapiens_tRNA-Pro-AGG-2-5 (tRNAscan-SE ID: chr14.trna24) chr14:21077495-21077566 (-) Pro (AGG) 72 bp Sc: 67.7;Homo_sapiens_tRNA-Pro-AGG-2-6 (tRNAscan-SE ID: chr14.trna23) chr14:21081560-21081631 (-) Pro (AGG) 72 bp Sc: 67.7;Homo_sapiens_tRNA-Pro-AGG-2-7 (tRNAscan-SE ID: chr16.trna29) chr16:3232635-3232706 (-) Pro (AGG) 72 bp Sc: 67.7;Homo_sapiens_tRNA-Pro-AGG-2-8 (tRNAscan-SE ID: chr16.trna10) chr16:3239634-3239705 (+) Pro (AGG) 72 bp Sc: 67.7
-
Homo_sapiens_tRNA-Ser-AGA-2-1 (tRNAscan-SE ID: chr6.trna5) chr6:26327817-26327898 (+) Ser (AGA) 82 bp Sc: 89.6;Homo_sapiens_tRNA-Ser-AGA-2-2 (tRNAscan-SE ID: chr6.trna44) chr6:27446591-27446672 (+) Ser (AGA) 82 bp Sc: 89.6;Homo_sapiens_tRNA-Ser-AGA-2-3 (tRNAscan-SE ID: chr6.trna46) chr6:27463593-27463674 (+) Ser (AGA) 82 bp Sc: 89.6;Homo_sapiens_tRNA-Ser-AGA-2-4 (tRNAscan-SE ID: chr6.trna47) chr6:27470818-27470899 (+) Ser (AGA) 82 bp Sc: 89.6;Homo_sapiens_tRNA-Ser-AGA-2-5 (tRNAscan-SE ID: chr8.trna9) chr8:96281885-96281966 (-) Ser (AGA) 82 bp Sc: 89.6;Homo_sapiens_tRNA-Ser-AGA-2-6 (tRNAscan-SE ID: chr17.trna35) chr17:8129928-8130009 (-) Ser (AGA) 82 bp Sc: 89.6
-
Homo_sapiens_tRNA-Ser-GCT-4-1 (tRNAscan-SE ID: chr6.trna124) chr6:28565117-28565198 (-) Ser (GCT) 82 bp Sc: 88.1;Homo_sapiens_tRNA-Ser-GCT-4-2 (tRNAscan-SE ID: chr15.trna11) chr15:40886023-40886104 (-) Ser (GCT) 82 bp Sc: 88.1;Homo_sapiens_tRNA-Ser-GCT-4-3 (tRNAscan-SE ID: chr17.trna6) chr17:8090184-8090265 (+) Ser (GCT) 82 bp Sc: 88.1
-
Homo_sapiens_tRNA-Val-CAC-1-1 (tRNAscan-SE ID: chr1.trna78) chr1:161369490-161369562 (-) Val (CAC) 73 bp Sc: 78.8;Homo_sapiens_tRNA-Val-CAC-1-2 (tRNAscan-SE ID: chr5.trna5) chr5:180524070-180524142 (+) Val (CAC) 73 bp Sc: 78.8;Homo_sapiens_tRNA-Val-CAC-1-3 (tRNAscan-SE ID: chr5.trna21) chr5:180529253-180529325 (-) Val (CAC) 73 bp Sc: 78.8;Homo_sapiens_tRNA-Val-CAC-1-4 (tRNAscan-SE ID: chr5.trna9) chr5:180600650-180600722 (+) Val (CAC) 73 bp Sc: 78.8;Homo_sapiens_tRNA-Val-CAC-1-5 (tRNAscan-SE ID: chr5.trna13) chr5:180649395-180649467 (-) Val (CAC) 73 bp Sc: 78.8;Homo_sapiens_tRNA-Val-CAC-1-6 (tRNAscan-SE ID: chr6.trna9) chr6:26538282-26538354 (+) Val (CAC) 73 bp Sc: 78.8
-
Homo_sapiens_tRNA-Val-TAC-1-1 (tRNAscan-SE ID: chr11.trna19) chr11:59318102-59318174 (-) Val (TAC) 73 bp Sc: 78.8;Homo_sapiens_tRNA-Val-TAC-1-2 (tRNAscan-SE ID: chrX.trna4) chrX:18693029-18693101 (-) Val (TAC) 73 bp Sc: 78.8
-
SNORD22;snoID_0137
-

# try m5C

## columns that I need for data
    chrom       "PositionC"[0]
    chromStart  "PositionC"[1]
    chromEnd    
    name        m3C
    score       BS_FDR
    strand      Strand
    thickStart   
    thickEnd    
    itemRGB     figure it out
    coverage    BS_Depth
    frequency   BS_%_non-converted
    
## information that I need for header
    organism human
    modification_type RNA
    assembly GRCh37
    annotation_source None
    annotation_version None
    sequencing_platform Illumina HiSeq 2500 (Illumina MiSeq for Psi data!!!!!)
    bioinformatics_workflow https://github.com/HuntsmanCancerInstitute/RBSSeqTools/
    experiment https://doi.org/10.1073/pnas.1817334116
    external_source SRA:SRP093982
    methods RBS-seq
    references pubmed_id:30872485
    conversion_information

In [2]:
keys = parse_excel("/home/annebusch/anne02/euf-data/rbs-seq/GSE90963_Table_S1-m5C_candidate_sites.xlsx")
keys

dict_keys(['Table Legends & Header Info', '1.High-threshold m5C candidates', '2.All m5C candidate sites', '3. RBS-Seq m5C Intersection'])

In [3]:
df = pd.read_excel("/home/annebusch/anne02/euf-data/rbs-seq/GSE90963_Table_S1-m5C_candidate_sites.xlsx", sheet_name="1.High-threshold m5C candidates")
df

,PositionC,Strand,Gene,Biotype,Classification,mRNA location,BS_Depth,BS_C+T,BS_C,BS_T,...,NBS_C+T,NBS_C,NBS_T,Cluster,Cluster Nonconverted,Reverse-complement,Reverse-complement Nonconverted,Splice,Other,Passes Thresholds
0,chr1:1277769,-,DVL1,protein_coding,protein_coding,exonic,88,31,57,88,...,58,58,0,0,0,0,0,1,0,1
1,chr1:150530042,+,ADAMTSL4,protein_coding,protein_coding,exonic,120,29,91,120,...,37,37,0,0,0,0,0,1,0,1
2,chr1:153665882,+,NPR1,protein_coding,protein_coding,exonic,22,14,8,22,...,60,60,0,0,0,0,0,0,0,1
3,chr1:155030158,+,ADAM15,protein_coding,protein_coding,exonic,192,66,126,192,...,148,148,0,0,0,0,0,0,0,1
4,chr1:155158511,-,MUC1,protein_coding,protein_coding,UTR3,98,92,5,97,...,23,23,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,tRNA_60:47,+,Homo_sapiens_tRNA-Ala-TGC-7-1 (tRNAscan-SE ID:...,tRNA,tRNA,.,3208,3207,2895,312,...,132,132,0,0,0,0,0,0,0,1
482,tRNA_63:49,+,Homo_sapiens_tRNA-Arg-ACG-1-1 (tRNAscan-SE ID:...,tRNA,tRNA,.,1004,1004,452,552,...,2936,2935,1,0,0,0,0,0,0,1
483,tRNA_64:49,+,Homo_sapiens_tRNA-Arg-ACG-2-1 (tRNAscan-SE ID:...,tRNA,tRNA,.,859,859,312,547,...,22460,22453,7,0,0,0,0,0,0,1
484,tRNA_78:61,+,Homo_sapiens_tRNA-Arg-TCT-1-1 (tRNAscan-SE ID:...,tRNA,tRNA,.,224,224,98,126,...,7166,7164,2,1,0,0,0,0,0,1
485,tRNA_82:50,+,Homo_sapiens_tRNA-Arg-TCT-4-1 (tRNAscan-SE ID:...,tRNA,tRNA,.,88,81,72,9,...,438,438,0,1,0,0,0,0,0,1

In [4]:
mask = df["PositionC"].str.startswith("chr")

df_chrom = df[mask]
df_non_chrom = df[~mask]

In [5]:
df_chrom

,PositionC,Strand,Gene,Biotype,Classification,mRNA location,BS_Depth,BS_C+T,BS_C,BS_T,...,NBS_C+T,NBS_C,NBS_T,Cluster,Cluster Nonconverted,Reverse-complement,Reverse-complement Nonconverted,Splice,Other,Passes Thresholds
0,chr1:1277769,-,DVL1,protein_coding,protein_coding,exonic,88,31,57,88,...,58,58,0,0,0,0,0,1,0,1
1,chr1:150530042,+,ADAMTSL4,protein_coding,protein_coding,exonic,120,29,91,120,...,37,37,0,0,0,0,0,1,0,1
2,chr1:153665882,+,NPR1,protein_coding,protein_coding,exonic,22,14,8,22,...,60,60,0,0,0,0,0,0,0,1
3,chr1:155030158,+,ADAM15,protein_coding,protein_coding,exonic,192,66,126,192,...,148,148,0,0,0,0,0,0,0,1
4,chr1:155158511,-,MUC1,protein_coding,protein_coding,UTR3,98,92,5,97,...,23,23,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,chrX:24095382,+,"AluSx,EIF2S3","Repbase,protein_coding",protein_coding,UTR3,267,101,166,267,...,119,119,0,0,0,0,0,0,0,1
185,chrX:55206634,-,.,.,ncRNA,.,304,105,199,304,...,5385,5383,2,1,0,0,0,0,0,1
186,chrX:86958997,-,RPSAP15,pseudogene,pseudogene,.,1162,234,928,1162,...,130,130,0,0,0,0,0,0,0,1
187,chrY:20777415,-,HUERS-P3b-int,Repbase,ncRNA,.,44,28,16,44,...,936,936,0,1,0,0,0,0,0,1
188,chrY:20866759,+,HUERS-P3b-int,Repbase,ncRNA,.,36,26,10,36,...,937,937,0,1,0,0,0,0,0,1

In [57]:
df_non_chrom = df_non_chrom.reset_index(drop=True)
df_non_chrom
tRNA = pd.read_csv("/home/annebusch/anne02/tRNA-index/human/hg19-tRNAs.bed", delimiter="\t", names = ["chrom", "start", "end", "trna", "score", "strand", "thickstart", "thickend", "zero", "num_exons", "length", "offset"], header=None)
del tRNA["zero"]
del tRNA["thickstart"]
del tRNA["thickend"]
del tRNA["score"]
tRNA['length'] = tRNA['length'].str.replace(',', '').astype(int)
tRNA['offset'] = tRNA['offset'].str.replace(',', '').astype(int)
tRNA

,chrom,start,end,trna,strand,num_exons,length,offset
0,chr1,7990338,7990408,tRNA-Und-NNN-4-1,-,1,70,0
1,chr1,16847079,16847153,tRNA-Asn-GTT-5-1,-,1,74,0
2,chr1,16858892,16858966,tRNA-Asn-GTT-18-1,-,1,74,0
3,chr1,16861773,16861845,tRNA-Glu-TTC-4-1,-,1,72,0
4,chr1,16872433,16872504,tRNA-Gly-CCC-1-1,-,1,71,0
...,...,...,...,...,...,...,...,...
591,chrX,3833270,3833344,tRNA-Ile-GAT-1-3,-,1,74,0
592,chrX,3833684,3833758,tRX-Ile-NNN-1-1,-,1,74,0
593,chrX,18693028,18693101,tRNA-Val-TAC-1-2,-,1,73,0
594,chrX,25280088,25280160,tRX-Ser-NNN-2-1,-,1,72,0
595,chrX,118737860,118737929,tRX-Pro-NNN-1-1,+,1,69,0

In [7]:
df_chrom.columns

Index(['PositionC', 'Strand', 'Gene', 'Biotype', 'Classification',
       'mRNA location', 'BS_Depth', 'BS_C+T', 'BS_C', 'BS_T',
       'BS_%_non-converted', 'BS_FDR', 'BS_Depth.1', 'BS_C+T.1', 'BS_C.1',
       'BS_T.1', 'BS_%_non-converted.1', 'BS_FDR.1', 'NBS_Depth', 'NBS_C+T',
       'NBS_C', 'NBS_T', 'Cluster', 'Cluster Nonconverted',
       'Reverse-complement', 'Reverse-complement Nonconverted', 'Splice',
       'Other', 'Passes Thresholds'],
      dtype='object')

,chrom,start,end,trna,strand,num_exons,length,offset
0,chr1,7990338,7990408,tRNA-Und-NNN-4-1,-,1,70,0
1,chr1,16847079,16847153,tRNA-Asn-GTT-5-1,-,1,74,0
2,chr1,16858892,16858966,tRNA-Asn-GTT-18-1,-,1,74,0
3,chr1,16861773,16861845,tRNA-Glu-TTC-4-1,-,1,72,0
4,chr1,16872433,16872504,tRNA-Gly-CCC-1-1,-,1,71,0
...,...,...,...,...,...,...,...,...
591,chrX,3833270,3833344,tRNA-Ile-GAT-1-3,-,1,74,0
592,chrX,3833684,3833758,tRX-Ile-NNN-1-1,-,1,74,0
593,chrX,18693028,18693101,tRNA-Val-TAC-1-2,-,1,73,0
594,chrX,25280088,25280160,tRX-Ser-NNN-2-1,-,1,72,0
595,chrX,118737860,118737929,tRX-Pro-NNN-1-1,+,1,69,0